spring.application.name=demo

server.servlet.context-path=/api

spring.datasource.url=jdbc:mysql://localhost:3306/bus

spring.datasource.username=root
spring.datasource.password=@AK005choco

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update

spring.jpa.show-sql=true

spring.jpa.properties.hibernate.format_sql=true

spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

# Email Configuration - Mailtrap
spring.mail.host=sandbox.smtp.mailtrap.io
spring.mail.port=2525
spring.mail.username=d8f3d3b6e8e42d
spring.mail.password=2f54b7c5bbdf00
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
<<<<<<< HEAD


logging.level.org.springframework=DEBUG
logging.level.root=DEBUG
=======
spring.mail.properties.mail.smtp.starttls.required=true
>>>>>>> 623bcda (Updated)
